version: '3.4'

services:
  userServicedb:
    image: postgres

  userservice.api:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: Services/UserService/UserService.API/Dockerfile

volumes:
  postgres_userService: