version: '3.4'

services:
  userServicedb:
    image: postgres

  catalogdb:
    image: postgres

  userservice.api:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: Services/UserService/UserService.API/Dockerfile

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

volumes:
  postgres_userService:
  postgres_catalog:  